### ISSUE TITLE
Add `OwnerWalkingCardView`.

### ISSUE THREAD

**Issue by iBYarchitect** [IronFoundation/iOS-Woof#77]
## TO DO:
Should the sitter's avatar be displayed, and should users be able to access a view with more information about the sitter by clicking on their profile?

## This task is a part of the issue:
 - #65 

## Depends on tasks:
- #_issue
- #_issue

## Description
Displays a card view with walk information: Sitter's name, date and time of the walk, and the cost.
These cards will be used in the list of available walks for the selected sitter.

## UI Mocks
![Image](https://github.com/IronFoundation/iOS-Woof/assets/103530508/2dd16689-7a89-4e21-80d6-c61fdb875875)

**Comment by NadzeyaShpakouskaya** [comment]
Implemented in PR #115
