### ISSUE TITLE
Add `BookWalking` View for owner flow

### ISSUE THREAD

**Issue by iBYarchitect** [IronFoundation/iOS-Woof#81]
## This task is a part of the issue:
 - #

## Depends on tasks:
- #72 
- #87 
- #83 

## Description
Create a booking screen for the selected available walk, where the pet owner can write notes and enter their address as text. Additionally, they should be able to choose a location on the map and set a pin. Also, a "Book Now" button should be displayed after filling in the necessary fields

## UI Mocks
<img width="382" alt="Screenshot 2024-01-25 at 09 37 47" src="https://github.com/IronFoundation/iOS-Woof/assets/32869814/e7be0d85-dc1d-4ee9-b74f-e7c4a9cf34de">
<img width="382" alt="Screenshot 2024-01-25 at 09 40 52" src="https://github.com/IronFoundation/iOS-Woof/assets/32869814/58bff1e2-9005-4911-ba72-8a2966f67aa2">

or 

<img width="382" alt="Screenshot 2024-01-25 at 14 31 22" src="https://github.com/IronFoundation/iOS-Woof/assets/32869814/caade200-038b-421c-8f1d-e99e66c8fb2e">
<img width="382" alt="Screenshot 2024-01-25 at 14 32 54" src="https://github.com/IronFoundation/iOS-Woof/assets/32869814/1d0d7422-20a6-4ba9-b15b-fc3c34f73278">

You are more than welcome to choose your design, but please follow App Style guidelines.

**Comment by NadzeyaShpakouskaya** [comment]
Please check the suggested UI or provide your option.
