### ISSUE TITLE
Add `Book walk` button in DetailPetSitterView.

### ISSUE THREAD

**Issue by iBYarchitect** [IronFoundation/iOS-Woof#84]
## This task is a part of the issue:
 - #issue

## Depends on tasks:
- #_issue
- #_issue

## UI Mocks
![image](https://github.com/IronFoundation/iOS-Woof/assets/103530508/02951fd7-9d03-49e7-ae7f-9bc594acef26)

**Comment by NadzeyaShpakouskaya** [comment]
Choose the other flow to book the walking #86
